{% set name = "readdy" %}
{% set version = "2.0.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4aa4eb3d8797fa28055823ac5ffbfc1b3f92a73f981ef4357ce4c33d3ad88322

build:
  number: 3
  skip: true  # [win]
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - conan
    - spdlog 1.10.0
    - nlohmann_json 3.10.3
    - fmt 8.1.1
    - pybind11 2.9.2
  host:
    - python
    - h5py
    - hdf5
    - zlib 1.2.*
    - blosc 1.21.1
    - numpy >=1.14
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - h5py
    - pint
    - tqdm
    - hdf5
    - zlib 1.2.*

test:
  imports:
    - readdy
  requires:
    - nose
  commands:
    - nosetests readdy -s -vv --with-doctest --doctest-options=+NORMALIZE_WHITESPACE,+ELLIPSIS

about:
  home: https://github.com/readdy/readdy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python / C++ based particle reaction-diffusion simulator'
  description: |
    ReaDDy (standing for [Rea]ction [D]iffusion [Dy]namics) is a particle based
    reaction-diffusion simulator that can be configured and run with Python 3.6+.
    The Python interface wraps around a C++ implementation for good performance.
    Trajectories are written using the flexible HDF5 format.
  doc_url: https://{{ name }}.github.io/
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - clonker
    - chrisfroe
